spring:
  profiles:
    default: development
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-poet.us.auth0.com/
server:
  servlet:
    context-path: /api/v1/

auth0:
  audience: poet-api-audience
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:poet
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  profiles: development
  datasource:
    url: jdbc:h2:file:~/Develop/poet/poet
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  profiles: production
  datasource:
    url: jdbc:h2:file:~/Develop/poet/poet
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create