spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-poet.us.auth0.com/
  datasource:
    url: jdbc:mysql://localhost:3306/poet
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
management:
  endpoints:
    web:
      exposure:
        include: mappings
auth0:
  audience: poet-api-audience
  nickname: https://poet.jax.org/nickname
  email: https://poet.jax.org/email
api:
  version: /api/v1
initializePoet: false
releasekey: release
