spring:
  profiles: test
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-poet.us.auth0.com/
  datasource:
    url: jdbc:h2:mem:poet
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
server:
  servlet:
    context-path: /api/v1/
auth0:
  audience: poet-api-audience
  nickname: https://poet.jax.org/nickname
  email: https://poet.jax.org/email
  role: https://poet.jax.org/role