server:
    servlet:
        context-path: /api/v1/
spring:
    datasource:
        url: jdbc:h2:file:~/Develop/poet/poet
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: create
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://dev-poet.us.auth0.com/