spring:
  datasource:
    url: jdbc:h2:file:./usr/local/svc-maxo/database/poet;mode=MYSQL
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-poet.us.auth0.com/
management:
  endpoints:
    web:
      exposure:
        include: health
auth0:
  audience: poet-api-audience
  nickname: https://poet.jax.org/nickname
  email: https://poet.jax.org/email
  role: https://poet.jax.org/role
api:
  version: /api/v1
  client: /,/portal/**

initializePoet: false