spring:
  profiles: stage
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-poet.us.auth0.com/
  datasource:
    url: jdbc:mariadb://localhost:3306/poet
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: mappings
auth0:
  audience: poet-api-audience
  nickname: https://poet.jax.org/nickname
  email: https://poet.jax.org/email
api:
  version: /api/v1
  client: /,/portal/**
initializePoet: false
