spring:
  profiles: test
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-poet.us.auth0.com/
  datasource:
    url: jdbc:h2:mem:poet
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
management:
  endpoints:
    web:
      exposure:
        include: mappings
auth0:
  audience: poet-api-audience
  nickname: https://poet.jax.org/nickname
  email: https://poet.jax.org/email
api:
  version: /api/v1
  client: /,/portal/**
initializePoet: false
releasekey: release
