spring:
  profiles: development
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-poet.us.auth0.com/
  datasource:
    url: jdbc:h2:file:~/Develop/poet/poet
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: mappings
auth0:
  audience: poet-api-audience
  nickname: https://poet.jax.org/nickname
  email: https://poet.jax.org/email
  role: https://poet.jax.org/role
api:
  version: /api/v1
  client: /,/portal/**
initializePoet: false
